# Random Forest model

In [5]:
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix
import numpy as np

# Load data
data_dict = pickle.load(open('./data.pickle', 'rb'))

# Convert data to numpy arrays
data = np.asarray(data_dict['data'])
labels = np.asarray(data_dict['labels'])

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle=True, stratify=labels)

# Create and train the model
model = RandomForestClassifier()
model.fit(x_train, y_train)

# Make predictions
y_predict = model.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_predict)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Calculate recall
recall = recall_score(y_test, y_predict, average='weighted')
print(f'Recall: {recall * 100:.2f}%')

# Calculate F1 Score
f1 = f1_score(y_test, y_predict, average='weighted')
print(f'F1 Score: {f1 * 100:.2f}%')

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_predict)
print('Confusion Matrix:')
print(conf_matrix)

# Save the trained model
with open('model.p', 'wb') as f:
    pickle.dump({'model': model}, f)


Accuracy: 100.00%
Recall: 100.00%
F1 Score: 100.00%
Confusion Matrix:
[[15  0  0 ...  0  0  0]
 [ 0 19  0 ...  0  0  0]
 [ 0  0  8 ...  0  0  0]
 ...
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0 17  0]
 [ 0  0  0 ...  0  0 19]]


# SVM model 

In [6]:
import pickle
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix
import numpy as np

# Load data
data_dict = pickle.load(open('./data.pickle', 'rb'))

data = np.asarray(data_dict['data'])
labels = np.asarray(data_dict['labels'])

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle=True, stratify=labels)

# Initialize the SVM model with RBF kernel
model = SVC(kernel='rbf')

# Train the model
model.fit(x_train, y_train)

# Make predictions
y_predict = model.predict(x_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_predict)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Calculate recall
recall = recall_score(y_test, y_predict, average='weighted')
print(f'Recall: {recall * 100:.2f}%')

# Calculate F1 Score
f1 = f1_score(y_test, y_predict, average='weighted')
print(f'F1 Score: {f1 * 100:.2f}%')

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_predict)
print('Confusion Matrix:')
print(conf_matrix)

# Save the model
with open('model.p', 'wb') as f:
    pickle.dump({'model': model}, f)


Accuracy: 98.65%
Recall: 98.65%
F1 Score: 98.27%
Confusion Matrix:
[[15  0  0 ...  0  0  0]
 [ 0 19  0 ...  0  0  0]
 [ 0  0  8 ...  0  0  0]
 ...
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0 17  0]
 [ 0  0  0 ...  0  0 19]]


##### After testing two models in real time for American Sign Language detection, we found that Support Vector Machine (SVM) outperformed the other model in separating similar classes, providing better accuracy and classification performance.